// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace api.CompiledModels
{
    [DbContext(typeof(ApiContext))]
    public partial class ApiContextModel : RuntimeModel
    {
        static ApiContextModel()
        {
            var model = new ApiContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ApiContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
