// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace api.CompiledModels
{
    public partial class ApiContextModel
    {
        partial void Initialize()
        {
            var craftman = CraftmanEntityType.Create(this);

            CraftmanEntityType.CreateAnnotations(craftman);

            AddAnnotation("ProductVersion", "7.0.13");
            AddAnnotation("Relational:MaxIdentifierLength", 64);
        }
    }
}
